const CalcApp = {
    title: 'Calculator',
    width: 320,
    height: 480,
    init: function(container, windowEl, winId) {
        container.innerHTML = `
            <div style="height:100%; display:flex; flex-direction:column; background:rgba(0,0,0,0.6); position:relative;">
                
                <!-- Calculator View -->
                <div id="calc-view" style="display:flex; flex-direction:column; height:100%;">
                    <div style="display:flex; justify-content:space-between; padding:5px 10px;">
                        <span style="color:var(--text-muted); font-size:12px;">Standard</span>
                        <button id="btn-2048" style="background:none; border:none; color:var(--accent); cursor:pointer; font-size:12px;">Play 2048</button>
                    </div>
                    <div id="calc-display" style="padding: 20px; font-size: 36px; text-align: right; color: #fff; flex-grow: 1; display:flex; align-items:flex-end; justify-content:flex-end; word-break:break-all;">0</div>
                    <div style="display: grid; grid-template-columns: repeat(4, 1fr); gap: 1px; background: rgba(255,255,255,0.1); padding:1px;">
                        <button class="calc-btn">C</button><button class="calc-btn">±</button><button class="calc-btn">%</button><button class="calc-btn" style="color:var(--accent)">/</button>
                        <button class="calc-btn">7</button><button class="calc-btn">8</button><button class="calc-btn">9</button><button class="calc-btn" style="color:var(--accent)">*</button>
                        <button class="calc-btn">4</button><button class="calc-btn">5</button><button class="calc-btn">6</button><button class="calc-btn" style="color:var(--accent)">-</button>
                        <button class="calc-btn">1</button><button class="calc-btn">2</button><button class="calc-btn">3</button><button class="calc-btn" style="color:var(--accent)">+</button>
                        <button class="calc-btn" style="grid-column: span 2;">0</button><button class="calc-btn">.</button><button class="calc-btn" style="background:var(--accent); color:#fff;">=</button>
                    </div>
                </div>

                <!-- 2048 Game View -->
                <div id="game-view" style="display:none; flex-direction:column; height:100%; padding:15px; box-sizing:border-box;">
                    <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:15px;">
                        <button id="btn-calc" style="background:none; border:none; color:var(--accent); cursor:pointer; font-size:12px;">&larr; Back</button>
                        <div style="text-align:right;">
                            <div style="font-size:12px; color:var(--text-muted);">SCORE <span id="g-score" style="color:#fff; font-weight:bold;">0</span></div>
                            <div style="font-size:12px; color:var(--text-muted);">BEST <span id="g-best" style="color:#fff; font-weight:bold;">0</span></div>
                        </div>
                    </div>
                    <div style="flex-grow:1; display:flex; align-items:center; justify-content:center;">
                        <div id="grid-container" style="background:rgba(255,255,255,0.1); padding:8px; border-radius:8px; display:grid; grid-template-columns:repeat(4, 1fr); grid-template-rows:repeat(4, 1fr); gap:8px; width:260px; height:260px;">
                            <!-- Cells generated by JS -->
                        </div>
                    </div>
                    <div style="text-align:center; margin-top:10px; color:var(--text-muted); font-size:12px;">
                        Use Arrow Keys or WASD to play.
                    </div>
                    <div id="game-over" style="display:none; position:absolute; top:0; left:0; width:100%; height:100%; background:rgba(0,0,0,0.8); flex-direction:column; align-items:center; justify-content:center; z-index:10;">
                        <h2 style="color:#fff; margin-bottom:5px;">Game Over!</h2>
                        <button id="btn-restart" class="app-btn" style="margin-top:15px;">Try Again</button>
                    </div>
                </div>

            </div>
        `;

        const calcView = container.querySelector('#calc-view');
        const gameView = container.querySelector('#game-view');
        const btn2048 = container.querySelector('#btn-2048');
        const btnCalc = container.querySelector('#btn-calc');

        // --- CALCULATOR LOGIC ---
        const display = container.querySelector('#calc-display');
        let current = '0';
        let previous = null;
        let operation = null;

        container.querySelectorAll('.calc-btn').forEach(btn => {
            btn.addEventListener('click', (e) => {
                if (window.SFX) window.SFX.click();
                const val = e.target.innerText;
                
                if (!isNaN(val) || val === '.') {
                    if (current === '0' && val !== '.') current = val;
                    else current += val;
                } else if (val === 'C') {
                    current = '0'; previous = null; operation = null;
                } else if (val === '±') {
                    current = (parseFloat(current) * -1).toString();
                } else if (val === '%') {
                    current = (parseFloat(current) / 100).toString();
                } else if (['+', '-', '*', '/'].includes(val)) {
                    previous = current;
                    current = '0';
                    operation = val;
                } else if (val === '=') {
                    if (operation && previous) {
                        const a = parseFloat(previous);
                        const b = parseFloat(current);
                        if (operation === '+') current = (a + b).toString();
                        if (operation === '-') current = (a - b).toString();
                        if (operation === '*') current = (a * b).toString();
                        if (operation === '/') current = (a / b).toString();
                        operation = null;
                        previous = null;
                    }
                }
                display.innerText = current;
            });
        });

        // --- VIEW SWITCHING ---
        btn2048.addEventListener('click', () => {
            if (window.SFX) window.SFX.click();
            calcView.style.display = 'none';
            gameView.style.display = 'flex';
            initGame();
        });
        
        btnCalc.addEventListener('click', () => {
            if (window.SFX) window.SFX.click();
            gameView.style.display = 'none';
            calcView.style.display = 'flex';
        });

        // --- 2048 LOGIC ---
        const gridEl = container.querySelector('#grid-container');
        const scoreEl = container.querySelector('#g-score');
        const bestEl = container.querySelector('#g-best');
        const gameOverEl = container.querySelector('#game-over');
        const btnRestart = container.querySelector('#btn-restart');

        let grid = [];
        let score = 0;
        let bestScore = localStorage.getItem('titanium_2048_best') || 0;
        bestEl.innerText = bestScore;
        
        const colors = {
            0: 'rgba(255,255,255,0.05)', 2: '#eee4da', 4: '#ede0c8', 8: '#f2b179',
            16: '#f59563', 32: '#f67c5f', 64: '#f65e3b', 128: '#edcf72',
            256: '#edcc61', 512: '#edc850', 1024: '#edc53f', 2048: '#edc22e'
        };

        const initGame = () => {
            grid = [[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]];
            score = 0;
            scoreEl.innerText = score;
            gameOverEl.style.display = 'none';
            addRandomTile();
            addRandomTile();
            drawGrid();
        };

        const addRandomTile = () => {
            let empty = [];
            for (let r=0; r<4; r++) {
                for (let c=0; c<4; c++) {
                    if (grid[r][c] === 0) empty.push({r,c});
                }
            }
            if (empty.length > 0) {
                const pos = empty[Math.floor(Math.random() * empty.length)];
                grid[pos.r][pos.c] = Math.random() < 0.9 ? 2 : 4;
            }
        };

        const drawGrid = () => {
            gridEl.innerHTML = '';
            for (let r=0; r<4; r++) {
                for (let c=0; c<4; c++) {
                    const val = grid[r][c];
                    const cell = document.createElement('div');
                    cell.style.backgroundColor = colors[val] || '#3c3a32';
                    cell.style.borderRadius = '4px';
                    cell.style.display = 'flex';
                    cell.style.alignItems = 'center';
                    cell.style.justifyContent = 'center';
                    cell.style.fontSize = val > 512 ? '14px' : '20px';
                    cell.style.fontWeight = 'bold';
                    cell.style.color = val > 4 ? '#fff' : '#776e65';
                    cell.innerText = val === 0 ? '' : val;
                    gridEl.appendChild(cell);
                }
            }
        };

        const slide = (row) => {
            let arr = row.filter(val => val);
            let missing = 4 - arr.length;
            let zeros = Array(missing).fill(0);
            return arr.concat(zeros);
        };

        const combine = (row) => {
            for (let i=0; i<3; i++) {
                if (row[i] !== 0 && row[i] === row[i+1]) {
                    row[i] *= 2;
                    row[i+1] = 0;
                    score += row[i];
                }
            }
            return row;
        };

        const moveLeft = () => {
            let moved = false;
            for (let r=0; r<4; r++) {
                let row = grid[r];
                let newRow = slide(combine(slide(row)));
                if (row.join(',') !== newRow.join(',')) moved = true;
                grid[r] = newRow;
            }
            return moved;
        };

        const moveRight = () => {
            let moved = false;
            for (let r=0; r<4; r++) {
                let row = grid[r].slice().reverse();
                let newRow = slide(combine(slide(row))).reverse();
                if (grid[r].join(',') !== newRow.join(',')) moved = true;
                grid[r] = newRow;
            }
            return moved;
        };

        const moveUp = () => {
            let moved = false;
            for (let c=0; c<4; c++) {
                let col = [grid[0][c], grid[1][c], grid[2][c], grid[3][c]];
                let newCol = slide(combine(slide(col)));
                for (let r=0; r<4; r++) {
                    if (grid[r][c] !== newCol[r]) moved = true;
                    grid[r][c] = newCol[r];
                }
            }
            return moved;
        };

        const moveDown = () => {
            let moved = false;
            for (let c=0; c<4; c++) {
                let col = [grid[0][c], grid[1][c], grid[2][c], grid[3][c]].reverse();
                let newCol = slide(combine(slide(col))).reverse();
                for (let r=0; r<4; r++) {
                    if (grid[r][c] !== newCol[r]) moved = true;
                    grid[r][c] = newCol[r];
                }
            }
            return moved;
        };

        const checkGameOver = () => {
            for (let r=0; r<4; r++) {
                for (let c=0; c<4; c++) {
                    if (grid[r][c] === 0) return false;
                    if (c !== 3 && grid[r][c] === grid[r][c+1]) return false;
                    if (r !== 3 && grid[r][c] === grid[r+1][c]) return false;
                }
            }
            return true;
        };

        const handleInput = (e) => {
            if (gameView.style.display === 'none') return;
            
            if (['ArrowLeft', 'ArrowRight', 'ArrowUp', 'ArrowDown', 'w', 'a', 's', 'd'].includes(e.key)) {
                e.preventDefault();
            }

            let moved = false;
            if (e.key === 'ArrowLeft' || e.key === 'a') moved = moveLeft();
            if (e.key === 'ArrowRight' || e.key === 'd') moved = moveRight();
            if (e.key === 'ArrowUp' || e.key === 'w') moved = moveUp();
            if (e.key === 'ArrowDown' || e.key === 's') moved = moveDown();

            if (moved) {
                if (window.SFX) window.SFX.click();
                addRandomTile();
                scoreEl.innerText = score;
                if (score > bestScore) {
                    bestScore = score;
                    bestEl.innerText = bestScore;
                    localStorage.setItem('titanium_2048_best', bestScore);
                }
                drawGrid();
                if (checkGameOver()) {
                    gameOverEl.style.display = 'flex';
                }
            }
        };

        windowEl.addEventListener('keydown', handleInput);
        btnRestart.addEventListener('click', initGame);
        
        // Focus management so keys work when window is active
        windowEl.setAttribute('tabindex', '-1');
        windowEl.style.outline = 'none';
        windowEl.addEventListener('mousedown', () => windowEl.focus());
    }
};
