const ImageViewerApp = {
    title: 'Image Viewer',
    width: 600,
    height: 450,
    init: function(container, windowEl, winId, initialData) {
        const filePath = initialData?.path;
        let content = '';
        if (filePath) {
            content = window.VFS.readFile(filePath) || '';
        }

        container.innerHTML = `
            <div style="display:flex; flex-direction:column; height:100%; background:rgba(0,0,0,0.8); position:relative;">
                
                <!-- IMAGE VIEW -->
                <div id="image-view" style="display:flex; flex-direction:column; height:100%;">
                    <div class="app-toolbar" style="background:rgba(255,255,255,0.05); padding:8px; display:flex; align-items:center; justify-content:space-between;">
                        <span style="color:var(--text-main); font-size:12px;">${filePath || 'No Image Loaded'}</span>
                        <button id="btn-play-puzzle" class="app-btn" style="color:var(--accent); font-weight:bold;">Play Slide Puzzle</button>
                    </div>
                    <div style="flex-grow:1; display:flex; align-items:center; justify-content:center; overflow:hidden; padding:20px;">
                        <img id="img-view" style="max-width:100%; max-height:100%; object-fit:contain; filter:drop-shadow(0 4px 12px rgba(0,0,0,0.5));" />
                    </div>
                </div>

                <!-- GAME VIEW -->
                <div id="game-view" style="display:none; flex-direction:column; height:100%;">
                    <div class="app-toolbar" style="background:rgba(255,255,255,0.05); padding:8px; display:flex; align-items:center; justify-content:space-between;">
                        <button id="btn-back-img" class="app-btn">&larr; Back</button>
                        <div style="font-size:12px; font-weight:bold;">MOVES: <span id="puzzle-moves" style="color:var(--accent);">0</span></div>
                        <button id="btn-restart-puzzle" class="app-btn">Shuffle</button>
                    </div>
                    <div style="flex-grow:1; display:flex; align-items:center; justify-content:center; padding:20px;">
                        <div id="puzzle-grid" style="display:grid; grid-template-columns:repeat(4, 1fr); grid-template-rows:repeat(4, 1fr); gap:2px; background:rgba(255,255,255,0.1); padding:2px; border-radius:4px; width:300px; height:300px;">
                            <!-- Tiles generated by JS -->
                        </div>
                    </div>
                    <div id="puzzle-overlay" style="display:none; position:absolute; top:0; left:0; width:100%; height:100%; background:rgba(0,0,0,0.8); flex-direction:column; align-items:center; justify-content:center; z-index:10;">
                        <h2 style="color:#4ade80; font-size:32px; margin-bottom:5px;">PUZZLE SOLVED!</h2>
                        <button id="btn-play-again" class="app-btn" style="margin-top:15px; padding:10px 20px;">Play Again</button>
                    </div>
                </div>
            </div>
        `;

        const imgView = container.querySelector('#image-view');
        const gameView = container.querySelector('#game-view');
        const btnPlay = container.querySelector('#btn-play-puzzle');
        const btnBack = container.querySelector('#btn-back-img');

        const gridEl = container.querySelector('#puzzle-grid');
        const movesEl = container.querySelector('#puzzle-moves');
        const overlay = container.querySelector('#puzzle-overlay');
        const btnRestart = container.querySelector('#btn-restart-puzzle');
        const btnPlayAgain = container.querySelector('#btn-play-again');

        const imgEl = container.querySelector('#img-view');
        
        let validImage = false;

        if (content.startsWith('data:image')) {
            imgEl.src = content;
            validImage = true;
        } else {
            imgEl.src = content;
            imgEl.onerror = () => {
                imgEl.outerHTML = '<div style="color:var(--text-muted); font-size:14px;">Invalid image data.</div>';
                validImage = false;
            };
        }

        let tiles = [];
        let emptyPos = 15;
        let moves = 0;
        let playing = false;

        const initPuzzle = () => {
            playing = true;
            moves = 0;
            movesEl.innerText = moves;
            overlay.style.display = 'none';
            gridEl.innerHTML = '';
            
            // Create solved array
            let arr = [];
            for (let i = 0; i < 16; i++) arr.push(i);
            
            // Shuffle (solvable logic)
            // A quick random walk from solved state guarantees solvability
            emptyPos = 15;
            for(let i = 0; i < 200; i++) {
                let neighbors = [];
                if (emptyPos % 4 !== 0) neighbors.push(emptyPos - 1);
                if (emptyPos % 4 !== 3) neighbors.push(emptyPos + 1);
                if (emptyPos >= 4) neighbors.push(emptyPos - 4);
                if (emptyPos < 12) neighbors.push(emptyPos + 4);
                
                let swapPos = neighbors[Math.floor(Math.random() * neighbors.length)];
                let temp = arr[emptyPos];
                arr[emptyPos] = arr[swapPos];
                arr[swapPos] = temp;
                emptyPos = swapPos;
            }

            tiles = arr;
            drawGrid();
        };

        const drawGrid = () => {
            gridEl.innerHTML = '';
            for (let i = 0; i < 16; i++) {
                let val = tiles[i];
                let cell = document.createElement('div');
                if (val === 15) {
                    cell.style.background = 'transparent';
                } else {
                    cell.style.background = validImage ? `url(${imgEl.src})` : 'linear-gradient(45deg, #1e90ff, #ff4757)';
                    cell.style.backgroundSize = '300px 300px';
                    // Calculate background position
                    let bx = (val % 4) * (100 / 3);
                    let by = Math.floor(val / 4) * (100 / 3);
                    cell.style.backgroundPosition = `${bx}% ${by}%`;
                    
                    cell.style.display = 'flex';
                    cell.style.alignItems = 'center';
                    cell.style.justifyContent = 'center';
                    cell.style.color = 'rgba(255,255,255,0.8)';
                    cell.style.fontSize = '24px';
                    cell.style.fontWeight = 'bold';
                    cell.style.textShadow = '0 2px 4px rgba(0,0,0,0.8)';
                    // cell.innerText = val + 1; // Uncomment to show numbers
                    cell.style.cursor = 'pointer';
                    cell.style.borderRadius = '2px';
                    cell.style.boxShadow = 'inset 0 0 0 1px rgba(255,255,255,0.2)';
                    
                    cell.addEventListener('mousedown', () => moveTile(i));
                }
                gridEl.appendChild(cell);
            }
        };

        const moveTile = (index) => {
            if (!playing) return;
            // Check if adjacent to empty (emptyPos is in 'tiles')
            let eIdx = tiles.indexOf(15);
            
            let isAdjacent = false;
            if (index === eIdx - 1 && eIdx % 4 !== 0) isAdjacent = true; // left
            if (index === eIdx + 1 && eIdx % 4 !== 3) isAdjacent = true; // right
            if (index === eIdx - 4) isAdjacent = true; // top
            if (index === eIdx + 4) isAdjacent = true; // bottom

            if (isAdjacent) {
                if (window.SFX) window.SFX.click();
                let temp = tiles[index];
                tiles[index] = tiles[eIdx];
                tiles[eIdx] = temp;
                moves++;
                movesEl.innerText = moves;
                drawGrid();
                checkWin();
            }
        };

        const checkWin = () => {
            for (let i = 0; i < 15; i++) {
                if (tiles[i] !== i) return;
            }
            // Won!
            playing = false;
            overlay.style.display = 'flex';
            
            // Fill the empty tile to show full image
            tiles[15] = 15; 
            gridEl.lastChild.style.background = validImage ? `url(${imgEl.src})` : 'linear-gradient(45deg, #1e90ff, #ff4757)';
            gridEl.lastChild.style.backgroundSize = '300px 300px';
            gridEl.lastChild.style.backgroundPosition = '100% 100%';
        };

        btnPlay.addEventListener('click', () => {
            if (window.SFX) window.SFX.click();
            imgView.style.display = 'none';
            gameView.style.display = 'flex';
            initPuzzle();
        });

        btnBack.addEventListener('click', () => {
            if (window.SFX) window.SFX.click();
            gameView.style.display = 'none';
            imgView.style.display = 'flex';
            playing = false;
        });

        btnRestart.addEventListener('click', () => {
            if (window.SFX) window.SFX.click();
            initPuzzle();
        });
        
        btnPlayAgain.addEventListener('click', () => {
            if (window.SFX) window.SFX.click();
            initPuzzle();
        });
    }
};
